_target_: src.datamodules.chatbot_datamodule.ChatbotDataModule

pretrained_model_name_or_path: ${model.pretrained_model_name_or_path}
data_dir: ${paths.data_dir}predict.csv
batch_size: 512
num_workers: 4
pin_memory: False
max_length: 256